export const GROUP_LABELS = {
  vowels: "Vokale",
  k: "カ行 (K)",
  s: "サ行 (S)",
  t: "タ行 (T)",
  n: "ナ行 (N)",
  h: "ハ行 (H)",
  m: "マ行 (M)",
  y: "ヤ行 (Y)",
  r: "ラ行 (R)",
  w: "ワ行 (W) · ン",
  g: "ガ行 (G)",
  z: "ザ行 (Z)",
  d: "ダ行 (D)",
  b: "バ行 (B)",
  p: "パ行 (P)",
};

export const KATAKANA_DATA = [
  // Lektion 1 (46 Grundzeichen)
  { char: "ア", rom: "a", group: "vowels", lesson: 1 },
  { char: "イ", rom: "i", group: "vowels", lesson: 1 },
  { char: "ウ", rom: "u", group: "vowels", lesson: 1 },
  { char: "エ", rom: "e", group: "vowels", lesson: 1 },
  { char: "オ", rom: "o", group: "vowels", lesson: 1 },

  { char: "カ", rom: "ka", group: "k", lesson: 1 },
  { char: "キ", rom: "ki", group: "k", lesson: 1 },
  { char: "ク", rom: "ku", group: "k", lesson: 1 },
  { char: "ケ", rom: "ke", group: "k", lesson: 1 },
  { char: "コ", rom: "ko", group: "k", lesson: 1 },

  { char: "サ", rom: "sa", group: "s", lesson: 1 },
  { char: "シ", rom: "shi", group: "s", lesson: 1 },
  { char: "ス", rom: "su", group: "s", lesson: 1 },
  { char: "セ", rom: "se", group: "s", lesson: 1 },
  { char: "ソ", rom: "so", group: "s", lesson: 1 },

  { char: "タ", rom: "ta", group: "t", lesson: 1 },
  { char: "チ", rom: "chi", group: "t", lesson: 1 },
  { char: "ツ", rom: "tsu", group: "t", lesson: 1 },
  { char: "テ", rom: "te", group: "t", lesson: 1 },
  { char: "ト", rom: "to", group: "t", lesson: 1 },

  { char: "ナ", rom: "na", group: "n", lesson: 1 },
  { char: "ニ", rom: "ni", group: "n", lesson: 1 },
  { char: "ヌ", rom: "nu", group: "n", lesson: 1 },
  { char: "ネ", rom: "ne", group: "n", lesson: 1 },
  { char: "ノ", rom: "no", group: "n", lesson: 1 },

  { char: "ハ", rom: "ha", group: "h", lesson: 1 },
  { char: "ヒ", rom: "hi", group: "h", lesson: 1 },
  { char: "フ", rom: "fu", group: "h", lesson: 1 },
  { char: "ヘ", rom: "he", group: "h", lesson: 1 },
  { char: "ホ", rom: "ho", group: "h", lesson: 1 },

  { char: "マ", rom: "ma", group: "m", lesson: 1 },
  { char: "ミ", rom: "mi", group: "m", lesson: 1 },
  { char: "ム", rom: "mu", group: "m", lesson: 1 },
  { char: "メ", rom: "me", group: "m", lesson: 1 },
  { char: "モ", rom: "mo", group: "m", lesson: 1 },

  { char: "ヤ", rom: "ya", group: "y", lesson: 1 },
  { char: "ユ", rom: "yu", group: "y", lesson: 1 },
  { char: "ヨ", rom: "yo", group: "y", lesson: 1 },

  { char: "ラ", rom: "ra", group: "r", lesson: 1 },
  { char: "リ", rom: "ri", group: "r", lesson: 1 },
  { char: "ル", rom: "ru", group: "r", lesson: 1 },
  { char: "レ", rom: "re", group: "r", lesson: 1 },
  { char: "ロ", rom: "ro", group: "r", lesson: 1 },

  { char: "ワ", rom: "wa", group: "w", lesson: 1 },
  { char: "ヲ", rom: "wo", group: "w", lesson: 1 },
  { char: "ン", rom: "n", group: "w", lesson: 1 },

  // Lektion 2 (25 Dakuten & Handakuten-Zeichen)
  { char: "ガ", rom: "ga", group: "g", lesson: 2 },
  { char: "ギ", rom: "gi", group: "g", lesson: 2 },
  { char: "グ", rom: "gu", group: "g", lesson: 2 },
  { char: "ゲ", rom: "ge", group: "g", lesson: 2 },
  { char: "ゴ", rom: "go", group: "g", lesson: 2 },

  { char: "ザ", rom: "za", group: "z", lesson: 2 },
  { char: "ジ", rom: "ji", group: "z", lesson: 2 },
  { char: "ズ", rom: "zu", group: "z", lesson: 2 },
  { char: "ゼ", rom: "ze", group: "z", lesson: 2 },
  { char: "ゾ", rom: "zo", group: "z", lesson: 2 },

  { char: "ダ", rom: "da", group: "d", lesson: 2 },
  { char: "ヂ", rom: "ji", group: "d", lesson: 2 },
  { char: "ヅ", rom: "zu", group: "d", lesson: 2 },
  { char: "デ", rom: "de", group: "d", lesson: 2 },
  { char: "ド", rom: "do", group: "d", lesson: 2 },

  { char: "バ", rom: "ba", group: "b", lesson: 2 },
  { char: "ビ", rom: "bi", group: "b", lesson: 2 },
  { char: "ブ", rom: "bu", group: "b", lesson: 2 },
  { char: "ベ", rom: "be", group: "b", lesson: 2 },
  { char: "ボ", rom: "bo", group: "b", lesson: 2 },

  { char: "パ", rom: "pa", group: "p", lesson: 2 },
  { char: "ピ", rom: "pi", group: "p", lesson: 2 },
  { char: "プ", rom: "pu", group: "p", lesson: 2 },
  { char: "ペ", rom: "pe", group: "p", lesson: 2 },
  { char: "ポ", rom: "po", group: "p", lesson: 2 },
];

export const WORD_DATA = [
  // Lektion 1
  {
    word: "アメリカ",
    rom: "amerika",
    german: "USA",
    category: "Land",
    lesson: 1,
  },
  {
    word: "イギリス",
    rom: "igirisu",
    german: "Großbritannien",
    category: "Land",
    lesson: 1,
  },
  {
    word: "インド",
    rom: "indo",
    german: "Indien",
    category: "Land",
    lesson: 1,
  },
  {
    word: "インドネシア",
    rom: "indoneshia",
    german: "Indonesien",
    category: "Land",
    lesson: 1,
  },
  { word: "タイ", rom: "tai", german: "Thailand", category: "Land", lesson: 1 },
  {
    word: "ドイツ",
    rom: "doitsu",
    german: "Deutschland",
    category: "Land",
    lesson: 1,
  },
  {
    word: "ブラジル",
    rom: "burajiru",
    german: "Brasilien",
    category: "Land",
    lesson: 1,
  },
  {
    word: "マイク・ミラー",
    rom: "maiku miraa",
    german: "Mike Miller",
    category: "Person",
    lesson: 1,
  },
  {
    word: "サントス",
    rom: "santosu",
    german: "Santos",
    category: "Person",
    lesson: 1,
  },
  {
    word: "カリナ",
    rom: "karina",
    german: "Karina",
    category: "Person",
    lesson: 1,
  },
  { word: "ワン", rom: "wan", german: "Wang", category: "Person", lesson: 1 },
  {
    word: "タワポン",
    rom: "tawapon",
    german: "Tawapong",
    category: "Person",
    lesson: 1,
  },
  {
    word: "テレサ",
    rom: "teresa",
    german: "Teresa",
    category: "Person",
    lesson: 1,
  },
  {
    word: "IMC",
    rom: "ai-emu-shii",
    german: "IMC",
    category: "Firma",
    lesson: 1,
  },
  {
    word: "パワーでんき",
    rom: "pawaa denki",
    german: "Power Denki",
    category: "Firma",
    lesson: 1,
  },
  {
    word: "ブラジルエアー",
    rom: "burajiru eaa",
    german: "Brasil Air",
    category: "Firma",
    lesson: 1,
  },
  {
    word: "AKC",
    rom: "ee-kee-shii",
    german: "AKC",
    category: "Institut",
    lesson: 1,
  },
];
